name: 🐛 Bug report
description: Create a bug report to help us improve the Figma Github Integration Widget
title : "[Bug]: "
labels:
 - bug
projects:
 - layooops/3
assignees:
 - vitaliiastakhov
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug.
      placeholder: I encountered a bug when...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
      placeholder: I expected that...
    validations:
      required: true
